### ISSUE TITLE
r-universe for all the `roll*` suite

### ISSUE THREAD

**Issue by timelyportfolio** [jjf234/rollport#1]
Hi, so happy to have found your great work on `roll*` suite of packages through the R in Finance speaker site.  Look forward to hearing your presentation and hopefully meeting you there.  I was wondering if you might be interested in setting up your own `roll*` r-universe which only contains `roll` currently https://jasonjfoster.r-universe.dev/builds.  I would really enjoy playing with all of the `roll*` packages, and given my setup (corporate security limitations or through `webr`), this would be much easier if available at r-universe.

Thanks so much for sharing your packages.

**Comment by jasonjfoster** [comment]
Thanks for the positive feedback! Looking forward to the R/Finance conference as well. I'm open to the idea of releasing the `roll*` suite of packages but need to improve testing and performance. For example, the `rolloptim` and `rollshap` compute the analytical solutions which can affect the speed efficiency (and currently no tests for `rollshap` either).  Will also need to consider the cost-benefit of maintaining packages on CRAN too. Primarily developed these packages to better my understanding of the underlying algorithms but hope you find them useful as well.

**Comment by timelyportfolio** [comment]
Hi @jasonjfoster thanks so much for the response.  I wanted to clarify that r-universe does not require CRAN so does not have any of the sometimes very challenging issues of CRAN policies.  Also, while I understand your desire for tests, these are fully optional as well.   Effectively very similar to publishing/sharing on Github except r-universe provides a very convenient alternative mechanism for installation especially for people like me, such as `webr` for packages that require compilation.

For instance, here is mine https://github.com/timelyportfolio/timelyportfolio.r-universe.dev for CRAN and also very experimental packages.  This becomes https://timelyportfolio.r-universe.dev/builds.

**Comment by jasonjfoster** [comment]
Thanks for letting me know. I'm unfamiliar with r-universe and thought it was a CRAN-mirror of sorts. Anyway I have created an r-universe repo and json file with the `roll*` suite of packages available here now: https://jasonjfoster.r-universe.dev/. Hope this makes it easier and looking forward to anymore feedback.
